services:
  - type: web
    name: aftercallpro
    env: python
    plan: free
    buildCommand: bash render-build.sh
    startCommand: gunicorn app:app --timeout 120 --workers 2
    runtime: python
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: aftercallpro-db
          property: connectionString
      - key: STRIPE_SECRET_KEY
        sync: false
      - key: STRIPE_WEBHOOK_SECRET
        sync: false

databases:
  - name: aftercallpro-db
    databaseName: aftercallpro
    plan: free
